modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="AFL-3.0"
[[mods]]
modId="with_fire"
version="${file.jarVersion}"
displayName="With Fire"
logoFile="hot.png"
credits="someoneice"
authors="someoneice"
description='''
然而我并不想写简介x
'''

[[dependencies.with_fire]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.with_fire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
