modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="AFL-3.0"
[[mods]]
modId="with_fire"
version="${file.jarVersion}"
displayName="With Fire"
logoFile="hot.png"
credits="someoneice"
authors="someoneice"
description='''
然而我并不想写x
'''

[[dependencies.with_fire]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.with_fire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
